#SUBDIRS := $(wildcard */.)
#
#all: $(SUBDIRS)
#$(SUBDIRS):
#	$(MAKE) -C -f *.mk $@
#
#.PHONY: all $(SUBDIRS)
#
#SUB_LIBFT := lib42/libft/
##SUB_GNL := lib42/get_next_line/
##SUB_PRINT := lib42/ft_printf/
#
#
#all: $(SUB_GNL) $(SUB_LIBFT) $(SUB_PRINT)
#$(SUB_LIBFT):
#	$(MAKE) -C $(SUB_LIBFT)

lib_libft := libft